# Generated by Django 4.1.7 on 2023-09-19 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120)),
                ('type', models.CharField(default=None, max_length=120)),
                ('day', models.CharField(default=None, max_length=120)),
                ('week', models.IntegerField(default=None, null=True)),
                ('start_time', models.IntegerField(default=None)),
                ('date', models.DateField(default=None)),
                ('account', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Swap_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(default=0)),
                ('activity_1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='swap_request_sender', to='timetable.activity')),
                ('activity_2', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='swap_request_receiver', to='timetable.activity')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120)),
                ('notes', models.CharField(blank=True, default=None, max_length=320)),
                ('account', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
