# Generated by Django 4.1.7 on 2023-07-07 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=120)),
                ('type', models.CharField(default=None, max_length=120)),
                ('day', models.CharField(default=None, max_length=120)),
                ('start_time', models.IntegerField(default=None)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('date', models.DateField(default=None)),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
