# Generated by Django 4.1.4 on 2022-12-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('day', models.CharField(max_length=120)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('notes', models.CharField(max_length=1000)),
            ],
        ),
    ]
