# Generated by Django 4.1.7 on 2023-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='swap_request',
            name='state',
        ),
        migrations.AddField(
            model_name='swap_request',
            name='description',
            field=models.CharField(default=None, max_length=120, null=True),
        ),
    ]
