# Generated by Django 4.1.4 on 2022-12-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.FloatField(null=True),
        ),
    ]
